#include <iostream>
#include <string.h>
using namespace std;

int main()
{
	int Num1=10;
	int Num2=0;
	int Res;
	try		//Exception Genereator Block
	{
		if(Num2==0)
		{
			throw 100;
		}
		Res=Num1/Num2;		//This kind of bad logic give rise to the runtime errors, this is know Exception Generator Code
		cout<<"Res: "<<Res<<endl;
	}
	catch(int x)	//Exception Handler Block
	{
		cout<<"Exception Occurred: "<<x<<endl;
	}


	cout<<"Rest of the Program"<<endl;
	return 0;
}
int main2()
{
	int Num1=10;
	int Num2=0;
	int Res=Num1/Num2;		//This kind of bad logic give rise to the runtime errors
	cout<<"Res: "<<Res<<endl;
	return 0;
}

int main1()
{

	int status=10;
	if(status=0)	//bug
	{
		cout<<"if"<<endl;
	}
	else
	{
		cout<<"else"<<endl;
	}
	return 0;
	//return 0 //error: expected ';' before '}' token
}


